### ISSUE TITLE
error Library _loter_wrap.so not found

### ISSUE THREAD

**Issue by paulocecco** [bcm-uga/Loter#12]
Hi I'm trying to run Loter and after installing all dependecies packages I tried to follow the tutorial and keep getting this Error.

import loter.locanc.local_ancestry as lc
Traceback (most recent call last):

  File "<ipython-input-23-dfb86c010cb7>", line 1, in <module>
    import loter.locanc.local_ancestry as lc

  File "C:\Users\pecun\Loter\python-package\Loter\python-package\loter\locanc\local_ancestry.py", line 5, in <module>
    import loter.pipeline as lt

  File "C:\Users\pecun\Loter\python-package\Loter\python-package\loter\pipeline.py", line 6, in <module>
    import loter.opti as opti

  File "C:\Users\pecun\Loter\python-package\Loter\python-package\loter\opti.py", line 1, in <module>
    import loter.estimatea as esta

  File "C:\Users\pecun\Loter\python-package\Loter\python-package\loter\estimatea.py", line 5, in <module>
    import loter.datastruct.parameter as parameter

  File "C:\Users\pecun\Loter\python-package\Loter\python-package\loter\datastruct\parameter.py", line 4, in <module>
    from loter.find_lib import _LIB

  File "C:\Users\pecun\Loter\python-package\Loter\python-package\loter\find_lib.py", line 35, in <module>
    _LIB = _get_lib()

  File "C:\Users\pecun\Loter\python-package\Loter\python-package\loter\find_lib.py", line 28, in _get_lib
    raise LoterLibraryNotFound("Library `_loter_wrap.so` not found")

LoterLibraryNotFound: Library `_loter_wrap.so` not found

I read a person had this problem before so I tried to do what you told him/her to do, and so:

import sys;print(sys.path)
['C:\\Users\\pecun', 'C:\\Users\\pecun\\Anaconda3.1\\python37.zip', 'C:\\Users\\pecun\\Anaconda3.1\\DLLs', 'C:\\Users\\pecun\\Anaconda3.1\\lib', 'C:\\Users\\pecun\\Anaconda3.1', '', 'C:\\Users\\pecun\\Anaconda3.1\\lib\\site-packages', 'C:\\Users\\pecun\\Anaconda3.1\\lib\\site-packages\\win32', 'C:\\Users\\pecun\\Anaconda3.1\\lib\\site-packages\\win32\\lib', 'C:\\Users\\pecun\\Anaconda3.1\\lib\\site-packages\\Pythonwin', 'C:\\Users\\pecun\\Anaconda3.1\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\pecun\\.ipython', 'c:\\users\\pecun\\loter\\python-package\\loter\\python-package']

What could be happening?

**Comment by gdurif** [comment]
Hi,
The problem seems to be with the compilation of the underlying Loter C++ code. Saddly, Loter was not proofed for Windows, and I don't have access to a Windows machine at the moment to replicate the issue.
I would recommend that you use the Unix environment for Windows Cygwin (https://cygwin.com/), or the Windows Subsytem for Linux (WSL, https://docs.microsoft.com/en-us/windows/wsl/about) to emulate an Unix system and install (and run) Loter on your machine.
