### ISSUE TITLE
Error while import loter.locanc.local_ancestry as lc

### ISSUE THREAD

**Issue by paulocecco** [bcm-uga/Loter#19]
import loter.locanc.local_ancestry as lc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/loter-0.1-py2.7-linux-x86_64.egg/loter/locanc/local_ancestry.py", line 3, in <module>
    import pandas as pd
  File "/usr/local/lib/python2.7/dist-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/api.py", line 7, in <module>
    from pandas.core.arrays.integer import (
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/arrays/__init__.py", line 2, in <module>
    from .base import (ExtensionArray,    # noqa
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/arrays/base.py", line 21, in <module>
    from pandas.core import ops
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/ops.py", line 17, in <module>
    import pandas.compat as compat
AttributeError: 'module' object has no attribute 'compat'

**Comment by gdurif** [comment]
Hi, I guess the problem is with Python 2.7. We do not support it since Python 2.7 is not maintained anymore.
I would recommend to upload to Python3.X, you can either use the Python3 distribution available for your system or Anaconda distribution.

**Comment by gdurif** [comment]
Please, tell me the problem remains after upgrading.
